"""
Admin API router — pipeline management and key generation.
Requires admin role.
"""

import logging

from fastapi import APIRouter, Depends, HTTPException, status

from src.api.auth import TokenData, create_access_token, get_current_user
from src.api.schemas import TokenResponse
from src.security.crypto import generate_api_key

logger = logging.getLogger(__name__)
router = APIRouter()


def _require_admin(user: TokenData = Depends(get_current_user)) -> TokenData:
    if user.role != "admin":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Admin role required",
        )
    return user


@router.post("/token", response_model=TokenResponse, include_in_schema=False)
async def issue_token(
    subject: str,
    role: str = "viewer",
    user: TokenData = Depends(_require_admin),
) -> TokenResponse:
    """Issue a JWT for a given subject and role. Admin only."""
    token = create_access_token(subject=subject, role=role)
    return TokenResponse(access_token=token)


@router.post("/api-key", include_in_schema=False)
async def create_api_key(
    user: TokenData = Depends(_require_admin),
) -> dict:
    """Generate a new API key. Returns raw key once — store the hash only."""
    raw, hashed = generate_api_key()
    logger.info("New API key generated by %s", user.sub)
    return {
        "raw_key": raw,
        "hashed_key": hashed,
        "note": "Store only the hash. The raw key cannot be recovered after this response.",
    }
