CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS warehouse;
CREATE SCHEMA IF NOT EXISTS api;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS pipeline;

REVOKE ALL ON SCHEMA staging   FROM PUBLIC;
REVOKE ALL ON SCHEMA warehouse FROM PUBLIC;
REVOKE ALL ON SCHEMA audit     FROM PUBLIC;
REVOKE ALL ON SCHEMA pipeline  FROM PUBLIC;
GRANT USAGE ON SCHEMA api TO PUBLIC;
