CREATE TABLE IF NOT EXISTS warehouse.fact_observations (
    observation_sk      UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    city_sk             UUID        NOT NULL REFERENCES warehouse.dim_city(city_sk),
    date_key            INTEGER     NOT NULL REFERENCES warehouse.dim_date(date_key),
    time_key            INTEGER     NOT NULL REFERENCES warehouse.dim_time(time_key),
    condition_id        INTEGER     REFERENCES warehouse.dim_weather_condition(condition_id),
    city_id             BIGINT      NOT NULL,
    observed_at         TIMESTAMPTZ NOT NULL,
    pipeline_run_id     UUID,
    temp_celsius        NUMERIC(5,2),
    feels_like_celsius  NUMERIC(5,2),
    temp_min_celsius    NUMERIC(5,2),
    temp_max_celsius    NUMERIC(5,2),
    heat_index_celsius  NUMERIC(5,2),
    pressure_hpa        SMALLINT,
    humidity_pct        SMALLINT    CHECK (humidity_pct BETWEEN 0 AND 100),
    visibility_m        INTEGER     CHECK (visibility_m >= 0),
    wind_speed_ms       NUMERIC(6,2)CHECK (wind_speed_ms >= 0),
    wind_deg            SMALLINT    CHECK (wind_deg BETWEEN 0 AND 360),
    wind_gust_ms        NUMERIC(6,2),
    cloud_cover_pct     SMALLINT    CHECK (cloud_cover_pct BETWEEN 0 AND 100),
    is_daytime          BOOLEAN,
    dq_score            SMALLINT    CHECK (dq_score BETWEEN 0 AND 100),
    loaded_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_city_observed UNIQUE (city_id, observed_at)
);

CREATE TABLE IF NOT EXISTS warehouse.fact_daily_weather (
    daily_sk            UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    city_sk             UUID        NOT NULL REFERENCES warehouse.dim_city(city_sk),
    date_key            INTEGER     NOT NULL REFERENCES warehouse.dim_date(date_key),
    city_id             BIGINT      NOT NULL,
    city_name           VARCHAR(100),
    country             CHAR(2),
    avg_temp_celsius    NUMERIC(5,2),
    min_temp_celsius    NUMERIC(5,2),
    max_temp_celsius    NUMERIC(5,2),
    temp_range          NUMERIC(5,2) GENERATED ALWAYS AS
                        (max_temp_celsius - min_temp_celsius) STORED,
    stddev_temp         NUMERIC(6,3),
    avg_feels_like      NUMERIC(5,2),
    avg_humidity_pct    NUMERIC(4,1),
    max_humidity_pct    NUMERIC(4,1),
    avg_wind_speed_ms   NUMERIC(6,2),
    max_wind_speed_ms   NUMERIC(6,2),
    avg_pressure_hpa    NUMERIC(6,1),
    avg_visibility_m    NUMERIC(8,0),
    avg_cloud_pct       NUMERIC(4,1),
    dominant_condition  VARCHAR(50),
    daylight_minutes    SMALLINT,
    avg_dq_score        NUMERIC(4,1),
    observation_count   SMALLINT,
    loaded_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_city_date UNIQUE (city_id, date_key)
);
